from dataclasses import dataclass
from typing import NamedTuple

from panda3d.core import NodePath
from panda3d.core import Point3, Vec3, LColor

from galaxy.galaxy import Galaxy
from galaxy.sun import Sun
from galaxy.planet import Planet, OrbitLine, ParticleRing, Atmosphere
from galaxy.asteroid_belt import Asteroids, AsteroidBelt
from noise import PerlinCurlNoise3D


class RotationalComponent:
    """A class that uses PerlincurlNoise to calculate the force
       to be added to each particle's coordinates.
        Args:
            offset_1, offset2 (list):
                Offset the values significantly to avoid discontinuities.
                For example: offset_1 = [100, 200, 300], offset_2 = [500, 600, 700]
            noise_scale (float):
                The larger the noise_scale, the greater the particle motion.
                Must be non-zero
            flow_strength (float):
                The magnitude of the force generated by the vector field.
                The larger the value, the faster the particle moves.
                Must be non-zero
    """

    def __init__(self, offset_1, offset_2, noise_scale=1.05, flow_strength=3):
        self.noise_scale = noise_scale
        self.flow_strength = flow_strength
        self.noise = PerlinCurlNoise3D(offset_1, offset_2)

    def compute(self, pos, dt):
        curl = self.noise.curl_3d(*(pos * self.noise_scale))
        return curl * self.flow_strength * dt

    def __repr__(self):
        return f'noise_scale: {self.noise_scale}, flow_strength: {self.flow_strength}'


@dataclass(frozen=True)
class OrbitDetails:

    rx: float
    ry: float
    tilt: Vec3
    eccentricity: float
    delay: float = None
    planet_name: str = None

    @property
    def major_axis(self):
        return self.rx * 2

    @property
    def minor_axis(self):
        return self.ry * 2


@dataclass(frozen=True)
class RingDetails:

    color: LColor
    hpr: Vec3
    particle_size: float
    particle_cnt: int
    thickness: float
    planet_name: str = None


class AsteroidBeltDetails(NamedTuple):

    orbit: OrbitDetails
    asteroids: NodePath


@dataclass(frozen=True)
class AtmosphereDetails:

    hpr: Vec3
    scale: float
    planet_name: str = None


@dataclass(frozen=True)
class PlanetDetails:

    name: str
    speed: float
    scale: float
    orbit: OrbitDetails = None
    ring: RingDetails = None
    atmosphere: AtmosphereDetails = None
    asteroids: AsteroidBeltDetails = None

    def __post_init__(self):
        if self.orbit:
            object.__setattr__(self.orbit, 'planet_name', self.name)
            print(self.orbit)
        if self.ring:
            object.__setattr__(self.ring, 'planet_name', self.name)
            print(self.ring)
        if self.atmosphere:
            object.__setattr__(self.atmosphere, 'planet_name', self.name)
            print(self.atmosphere)

    @property
    def planet(self):
        return self.name, self.speed, self.scale, self.orbit


class Scene:

    def __init__(self):
        self.root = NodePath('root')
        self.root.reparent_to(base.render)

        self.galaxy = Galaxy()

        self.sun = Sun(Point3(0, 0, 0))
        self.sun.reparent_to(self.root)

        self.asteroids = Asteroids()
        # import pdb; pdb.set_trace()

        # self.planets = [
        #     Planet(rx=12.0, ry=9.0, speed=1.6, tilt=(15, 0, 5), scale=0.25, eccentricity=0.0, file='snow.bam'),
        #     Planet(rx=20.0, ry=15.0, speed=1.0, tilt=(-10, 25, 0), scale=0.4, eccentricity=0.2, file='desert.bam'),
        #     Planet(rx=29.0, ry=21.75, speed=0.6, tilt=(5, 45, -5), scale=0.6, eccentricity=0.45, file='earth.bam'),
        #     Planet(rx=38.0, ry=28.5, speed=0.3, tilt=(25, -20, 15), scale=0.45, eccentricity=0.55, file='green.bam'),
        #     Planet(rx=48.0, ry=36.0, speed=0.12, tilt=(-30, 10, 25), scale=0.65, eccentricity=0.6, file='Ice_20260702234839.bam'),
        # ]

        green = OrbitDetails(rx=12.0, ry=9.0, tilt=Vec3(15, 0, 5), eccentricity=0.0)
        snow = OrbitDetails(rx=20.0, ry=15.0, tilt=Vec3(-10, 25, 0), eccentricity=0.2)
        earth = OrbitDetails(rx=29.0, ry=21.75, tilt=Vec3(5, 45, -5), eccentricity=0.58)
        desert = OrbitDetails(rx=38.0, ry=28.5, tilt=Vec3(25, -20, 15), eccentricity=0.45)
        ice = OrbitDetails(rx=51.0, ry=38.25, tilt=Vec3(-10, -55, 25), eccentricity=0.6)

        atmosphere = AtmosphereDetails(hpr=Vec3(0, -30, 0), scale=Vec3(6.5))
        belt = AsteroidBeltDetails(orbit=desert, asteroids=self.asteroids)
        ring = RingDetails(color=LColor(0.58, 0.67, 0.74, 0.6), hpr=Vec3(0, 45, 0), particle_size=1.1, particle_cnt=2000, thickness=4)

        planet_details = [
            PlanetDetails(name='green', orbit=green, speed=1.6, scale=0.25),
            PlanetDetails(name='snow', orbit=snow, speed=1.0, scale=0.4, atmosphere=atmosphere),
            PlanetDetails(name='earth', orbit=earth, speed=0.6, scale=0.62),
            PlanetDetails(name='desert', orbit=desert, speed=0.3, scale=0.45, asteroids=belt),
            PlanetDetails(name='ice', orbit=ice, speed=0.12, scale=0.65, ring=ring),
        ]

        self.planets = []
        self.create_planets(planet_details)

    def create_planets(self, planet_details):
        for details in planet_details:
            planet = Planet(*details.planet)
            planet.reparent_to(self.root)
            self.planets.append(planet)

            orbit_line = OrbitLine(details.orbit)
            orbit_line.reparent_to(self.root)

            if details.asteroids is not None:
                belt = AsteroidBelt(*details.asteroids, planet)
                belt.reparent_to(self.root)
                self.planets.append(belt)

            if details.atmosphere is not None:
                atmosphere = Atmosphere(details.atmosphere)
                atmosphere.reparent_to(planet)

            if details.ring is not None:
                ring = ParticleRing(details.ring, planet)
                ring.reparent_to(planet.directional_nd)


        # for planet in self.planets:
        #     planet.reparent_to(self.root)

        #     orbit_line = OrbitLine(planet.orbit)
        #     orbit_line.reparent_to(self.root)


        #     if planet.speed == 0.3:
        #         self.debris = AsteroidBelt(self.asteroids, rx=38.0, ry=28.5, tilt=(25, -20, 15))
        #         self.debris.set_color(LColor(0.6, 0.37, 0.19, 1.0))
        #         self.debris.reparent_to(self.root)

        #     if planet.speed == 1.0:
        #         atmosphere = Atmosphere(Vec3(0, -30, 0), Vec3(6.5))
        #         atmosphere.reparent_to(planet)

        #     if planet.speed == 0.12:
        #         # !!!!! 惑星のサイズを取得するメソッドをPlanetに持たせる。引数の渡し方をもう少し考える!!!!!
        #         # !!!!! planetモジュールの各クラスに名前を渡せるようにする !!!!!

        #         ring = ParticleRing(planet, LColor(0.58, 0.67, 0.74, 0.6), 45)
        #         ring.reparent_to(planet.directional_nd)


    def update(self, dt):
        sun_pos = self.sun.get_pos()

        for planet in self.planets:
            planet.revolve(sun_pos, dt)