import array
import math
from dataclasses import dataclass
from direct.filter.CommonFilters import CommonFilters
from direct.showbase.ShowBaseGlobal import globalClock

from panda3d.core import NodePath, PandaNode, RenderAttrib
from panda3d.core import Point3, Vec3, LColor, LRotation, Camera
from panda3d.core import PNMImage, Texture, TextureStage, StackedPerlinNoise2
from direct.particles.ParticleEffect import ParticleEffect
from direct.particles.Particles import Particles
from direct.particles.ForceGroup import ForceGroup
from panda3d.core import TransparencyAttrib
from panda3d.core import Shader

from panda3d.core import ColorBlendAttrib, TextureStage

from panda3d.physics import PointParticleFactory
from panda3d.physics import SparkleParticleRenderer

from panda3d.physics import SphereSurfaceEmitter, BaseParticleRenderer
from panda3d.core import GeomVertexData, GeomVertexFormat
from panda3d.core import GeomEnums, Geom, GeomNode, GeomPoints
from panda3d.core import LQuaternion

from noise import PerlinNoise, SimplexNoise, TileableSimplexNoise, Fractal2D, TileablePerlinNoise, Fractal3D
from noise import PerlinCurlNoise3D
import numpy as np

from shapes import Plane, Box, EllipticalPrism
from shapes.create_geometry import ProceduralGeometry



@dataclass
class PlanetInfo:

    name: str
    rx: float
    ry: float
    speed: float
    tilt: Vec3
    scale: float
    eccentricity: float
    file: str

    def __post_init__(self):
        self.orbit_major_axis = self.rx * 2,
        self.orbit_minor_axis = self.ry * 2,

    def planet_model_info(self):
        pass

    def orbit_model_info(self):
        pass


class RotationalComponent:
    """A class that uses PerlincurlNoise to calculate the force
       to be added to each particle's coordinates.
        Args:
            offset_1, offset2 (list):
                Offset the values significantly to avoid discontinuities.
                For example: offset_1 = [100, 200, 300], offset_2 = [500, 600, 700]
            noise_scale (float):
                The larger the noise_scale, the greater the particle motion.
                Must be non-zero
            flow_strength (float):
                The magnitude of the force generated by the vector field.
                The larger the value, the faster the particle moves.
                Must be non-zero
    """

    def __init__(self, offset_1, offset_2, noise_scale=1.05, flow_strength=3):
        self.noise_scale = noise_scale
        self.flow_strength = flow_strength
        self.noise = PerlinCurlNoise3D(offset_1, offset_2)

    def compute(self, pos, dt):
        curl = self.noise.curl_3d(*(pos * self.noise_scale))
        return curl * self.flow_strength * dt

    def __repr__(self):
        return f'noise_scale: {self.noise_scale}, flow_strength: {self.flow_strength}'


class Galaxy(NodePath):

    def __init__(self, size=3000):
        super().__init__(PandaNode('galaxy'))
        box = Box(size, size, size).create()
        box.reparent_to(self)
        self.create_camera()

        shader = Shader.load(Shader.SL_GLSL, 'shaders/galaxy_v.glsl', 'shaders/galaxy_f.glsl')
        box.set_shader(shader)
        props = base.win.get_properties()
        win_size = props.get_size()
        box.set_shader_input('u_resolution', win_size)

    def create_camera(self):
        region = base.win.make_display_region(0, 1, 0, 1)
        cam = NodePath(Camera('sky_cam'))
        cam.node().set_lens(base.camLens)
        cam.reparent_to(self)
        region.set_camera(cam)
        region.set_sort(-1000)


class SolarFlare(NodePath):

    def __init__(self, sun):
        super().__init__(PandaNode('solar_flare'))
        # self.panel = Plane(15, 15, 4, 4).create()
        self.panel = Plane(20, 20, 4, 4).create()
        self.panel.reparent_to(self)
        self.set_transparency(TransparencyAttrib.MAlpha)
        self.set_pos(sun.get_pos())
        self.set_p(90)
        self.setBillboardPointEye()


        shader = Shader.load(Shader.SL_GLSL, 'shaders/flare_v.glsl', 'shaders/flare_f.glsl')
        self.set_shader(shader)


class Sun(NodePath):

    def __init__(self):
        super().__init__(PandaNode('sun'))
        self.model = base.loader.load_model('models/sun.bam')
        self.model.reparent_to(self)
        # self.set_scale(1.5)
        self.set_scale(2.0)
        self.setup_textures()
        base.task_mgr.add(self.update, 'update_sun')

    def create_texture_img(self):
        noise = TileablePerlinNoise()
        noise = Fractal2D(noise.pnoise2)

        size = 256
        img = PNMImage(size, size, 3)

        color_dark = LColor(0.3, 0.0, 0.0, 1.0)
        color_mid = LColor(1.0, 0.3, 0.0, 1.0)
        color_high = LColor(1.0, 0.9, 0.2, 1.0)

        for j, y in enumerate(np.linspace(0, 12, size)):
            for i, x in enumerate(np.linspace(0, 12, size)):
                if (val := noise.fractal(x, y)) < 0.5:
                    t = val * 2.0
                    final_color = color_dark * (1.0 - t) + color_mid * t
                else:
                    t = (val - 0.5) * 2.0
                    final_color = color_mid * (1.0 - t) + color_high * t

                img.set_xel(i, j, final_color.get_xyz())

        return img

    def setup_textures(self):
        img = self.create_texture_img()

        sun_tex = Texture()
        sun_tex.load(img)
        sun_tex.set_wrap_u(Texture.WM_repeat)
        sun_tex.set_wrap_v(Texture.WM_repeat)

        self.ts1 = TextureStage('sun_ts1')
        self.ts1.set_mode(TextureStage.M_modulate)
        self.set_texture(self.ts1, sun_tex)

        self.ts2 = TextureStage('sun_tx2')
        self.ts2.set_mode(TextureStage.M_add)
        self.set_texture(self.ts2, sun_tex)

        self.set_tex_scale(self.ts2, 1.5, 1.5)
        self.set_color_scale((2.0, 1.8, 1.2, 1.0))

    def update(self, task):
        dt = globalClock.get_dt()
        offset_u1 = task.time * 0.03
        offset_v1 = task.time * 0.02
        self.set_tex_offset(self.ts1, offset_u1, offset_v1)

        offset_u2 = task.time * -0.02
        offset_v2 = task.time * -0.04
        self.set_tex_offset(self.ts2, offset_u2, offset_v2)

        self.set_h(self.get_h() + 10 * dt)
        return task.cont


class Planet(NodePath):

    def __init__(self, rx, ry, speed, tilt, scale, eccentricity, file):
        super().__init__(PandaNode('sphere'))
        self.model = base.loader.load_model(f'models/{file}')
        self.model.reparent_to(self)
        self.set_scale(scale)

        self.rx = rx
        self.ry = ry
        self.speed = speed
        self.tilt = tilt
        self.eccentricity = eccentricity
        self.angle = 0
        self.max_distance = max(self.rx, self.ry) ** 2

    def orbit(self, sun_pos, dt):
        if self.angle > math.tau:
            self.angle -= math.tau

        seed_multiplier = 1.0 / (1.0 + self.eccentricity * math.cos(self.angle))
        self.angle += self.speed * seed_multiplier * dt

        x = math.cos(self.angle) * self.rx
        y = math.sin(self.angle) * self.ry
        pos = Vec3(x, y, 0)

        tilt_rot = LRotation(*self.tilt)
        tilted_pos = tilt_rot.xform(pos)
        final_pos = sun_pos + tilted_pos
        hpr = Vec3(self.get_h() + 50 * dt, 0, 0)
        self.set_pos_hpr(final_pos, hpr)


class Scene:

    def __init__(self):
        self.root = NodePath('root')
        self.root.reparent_to(base.render)

        self.galaxy = Galaxy()

        self.sun = Sun()
        self.sun.reparent_to(self.root)

        self.solar_flare = SolarFlare(self.sun)
        self.solar_flare.reparent_to(self.root)

        self.planets = [
            Planet(rx=12.0, ry=9.0, speed=1.6, tilt=(15, 0, 5), scale=0.25, eccentricity=0.0, file='snow.bam'),
            Planet(rx=20.0, ry=15.0, speed=1.0, tilt=(-10, 25, 0), scale=0.4, eccentricity=0.2, file='desert.bam'),
            Planet(rx=29.0, ry=21.75, speed=0.6, tilt=(5, 45, -5), scale=0.6, eccentricity=0.45, file='earth.bam'),
            Planet(rx=38.0, ry=28.5, speed=0.3, tilt=(25, -20, 15), scale=0.45, eccentricity=0.55, file='green.bam'),
            Planet(rx=48.0, ry=36.0, speed=0.12, tilt=(-30, 10, 25), scale=0.65, eccentricity=0.65, file='ice.bam'),
        ]
        self.create_planets()

    def create_planets(self):
        for planet in self.planets:
            planet.reparent_to(self.root)

            orbit_model = EllipticalPrism(
                major_axis=planet.rx * 2,
                minor_axis=planet.ry * 2,
                thickness=0.02,
                height=0.02
            ).create()

            orbit_model.set_hpr(planet.tilt)
            orbit_model.reparent_to(self.root)

    def update(self, dt):
        sun_pos = self.sun.get_pos()

        for planet in self.planets:
            planet.orbit(sun_pos, dt)