import random

from panda3d.core import NodePath, PandaNode
from panda3d.core import TransparencyAttrib
from panda3d.core import TextureStage
from panda3d.core import Vec3

from noise import PerlinCurlNoise3D
from shapes import PlaneForTextureAtlas


def nonzero_random(a, b):
    while True:
        if (num := round(random.uniform(a, b))) != 0:
            return num


class RotationalComponent:
    """A class that uses PerlincurlNoise to calculate the force
       to be added to each particle's coordinates.
        Args:
            offset_1, offset2 (list):
                Offset the values significantly to avoid discontinuities.
                For example: offset_1 = [100, 200, 300], offset_2 = [500, 600, 700]
            noise_scale (float):
                The larger the noise_scale, the greater the particle motion.
                Must be non-zero
            flow_strength (float):
                The magnitude of the force generated by the vector field.
                The larger the value, the faster the particle moves.
                Must be non-zero
    """

    def __init__(self, offset_1, offset_2, noise_scale=1.05, flow_strength=3):
        self.noise_scale = noise_scale
        self.flow_strength = flow_strength
        self.noise = PerlinCurlNoise3D(offset_1, offset_2)

    def compute(self, pos, dt):
        curl = self.noise.curl_3d(*(pos * self.noise_scale))
        return curl * self.flow_strength * dt

    def __repr__(self):
        return f'noise_scale: {self.noise_scale}, flow_strength: {self.flow_strength}'


class Debri:

    angular_speed = [20, 40, 60, 80, 100]

    def __init__(self, model, default_pos, rotational_component, scale_speed=0.2):
        self.model = model
        self.model.set_pos(default_pos)
        self.rotational_component = rotational_component
        self.scale_speed = scale_speed

    def update(self, dt):
        if self.model is None:
            return False

        if (scale := self.model.get_scale() - self.scale_speed * dt) <= 0:
            self.model.remove_node()
            self.model = None
            return False

        pos = self.model.get_pos()
        vec = self.rotational_component.compute(pos, dt)
        next_pos = pos + Vec3(*vec)

        angular_speed = random.choice(Debri.angular_speed)
        hpr = self.model.get_hpr() + Vec3(angular_speed * dt)

        self.model.set_pos_hpr_scale(next_pos, hpr, scale)
        return True


class RoguePlanet(NodePath):

    def __init__(self, asteroids, texture_atlas, start_pos, end_pos, scale, travel_speed):
        super().__init__(PandaNode('rogue_planet'))
        self.texture_atlas = texture_atlas
        self.start_pos = start_pos
        self.end_pos = end_pos
        self.distance = self.end_pos - self.start_pos
        self.travel_speed = travel_speed

        self.debris = []
        self.create_rogue_planet(asteroids)

        self.set_pos_hpr_scale(self.start_pos, Vec3(1), scale)
        self.set_texture(base.loader.load_texture('textures/silver.jpg'))

        self.progress = 0.0
        self.is_shattered = False
        self.effect = False

    def create_rogue_planet(self, asteroids):
        rotational_component = RotationalComponent(
            offset_1=[0, 0, 300],
            offset_2=[0, 0, 600],
            noise_scale=random.uniform(0.9, 3),
            flow_strength=nonzero_random(-3, 3)
        )

        for asteroid in asteroids.get_children():
            default_pos = asteroid.get_pos()
            model = asteroid.copy_to(self)
            scale_speed = round(random.uniform(0.1, 0.3), 2)
            debri = Debri(model, default_pos, rotational_component, scale_speed)
            self.debris.append(debri)

    def update(self, dt):
        if self.progress <= 1.2:
            self.progress += self.travel_speed * dt
            next_pos = self.start_pos + self.distance * self.progress

            if not self.is_shattered:
                hpr = Vec3(self.get_hpr() + 50 * dt)
                self.set_pos_hpr(next_pos, hpr)

                if self.progress >= 0.85:
                    self.is_shattered = True
                    self.vfx = VFX(self.texture_atlas)
                    self.effect = True

                return True

            self.set_pos(next_pos)

        if self.effect:
            if not self.vfx.run(self.get_pos()):
                self.effect = False

        cnt = 0
        for debri in self.debris:
            if debri.update(dt):
                cnt += 1

        return cnt > 0


class TextureAtlas(NodePath):

    def __init__(self, file_name, size=1, cols=8, rows=8):
        super().__init__(PandaNode('texture_atlas'))
        self.div_u = 1 / cols
        self.div_v = 1 / rows

        self.panel = PlaneForTextureAtlas(self.div_u, self.div_v, size).create()
        self.panel.reparent_to(self)

        self.set_transparency(TransparencyAttrib.MAlpha)
        self.tex = base.loader.load_texture(f'textures/{file_name}')
        self.set_texture(TextureStage.get_default(), self.tex, 1)
        self.set_bin('fixed', 40)
        self.set_depth_write(False)
        self.set_depth_test(False)
        self.set_light_off()
        self.flatten_light()
        self.set_billboard_point_eye()

        # starting position
        self.pos_u = -self.div_u
        self.pos_v = 0

    def animate(self):
        self.pos_u += self.div_u

        # go to the next row
        if self.pos_u >= 1.0:
            self.pos_u = 0
            self.pos_v -= self.div_v

        # comes to the end
        if self.pos_v <= -1.0:
            return False

        self.set_tex_offset(TextureStage.get_default(), self.pos_u, self.pos_v)
        return True


class VFX:
    """Use a texture atlas to depict the light emitted when the rogue planet explodes.
        tex (planet_details.TextureAtlasDetails):
            Details of the texture atlas, including an image filename, size, cols and rows.
    """

    def __init__(self, tex):
        self.texture_atlas = TextureAtlas(*tex)
        self.texture_atlas.reparent_to(base.render)

    def run(self, pos):
        self.texture_atlas.set_pos(pos)

        if not self.texture_atlas.animate():
            self.texture_atlas.remove_node()
            self.texture_atlas = None
            return False

        return True