import random

from panda3d.core import NodePath, PandaNode
from panda3d.core import Vec3

from noise import PerlinCurlNoise3D


class RotationalComponent:
    """A class that uses PerlincurlNoise to calculate the force
       to be added to each particle's coordinates.
        Args:
            offset_1, offset2 (list):
                Offset the values significantly to avoid discontinuities.
                For example: offset_1 = [100, 200, 300], offset_2 = [500, 600, 700]
            noise_scale (float):
                The larger the noise_scale, the greater the particle motion.
                Must be non-zero
            flow_strength (float):
                The magnitude of the force generated by the vector field.
                The larger the value, the faster the particle moves.
                Must be non-zero
    """

    def __init__(self, offset_1, offset_2, noise_scale=1.05, flow_strength=3):
        self.noise_scale = noise_scale
        self.flow_strength = flow_strength
        self.noise = PerlinCurlNoise3D(offset_1, offset_2)

    def compute(self, pos, dt):
        curl = self.noise.curl_3d(*(pos * self.noise_scale))
        return curl * self.flow_strength * dt

    def __repr__(self):
        return f'noise_scale: {self.noise_scale}, flow_strength: {self.flow_strength}'


class Debri:

    angular_speed = [20, 40, 60, 80, 100]

    def __init__(self, model, default_pos, rotational_component, scale_speed=0.2):
        self.model = model
        self.default_pos = default_pos
        self.rotational_component = rotational_component
        self.scale_speed = scale_speed
        self.model.set_pos(self.default_pos)
        self.is_removed = False

    def update(self, dt):
        if self.is_removed:
            # if self.is_empty():
            return False

        if (scale := self.model.get_scale() - self.scale_speed * dt) <= 0:
            self.model.remove_node()
            self.model = None
            self.is_removed = True
            return False

        pos = self.model.get_pos()
        vec = self.rotational_component.compute(pos, dt)
        next_pos = pos + Vec3(*vec)

        angular_speed = random.choice(Debri.angular_speed)
        hpr = self.model.get_hpr() + Vec3(angular_speed * dt)

        self.model.set_pos_hpr_scale(next_pos, hpr, scale)
        return True


class RoguePlanet(NodePath):

    def __init__(self, asteroids, start_pos, end_pos, scale=1.5, travel_speed=0.05):
        super().__init__(PandaNode('rogue_planet'))
        self.start_pos = start_pos
        self.end_pos = end_pos
        self.distance = self.end_pos - self.start_pos
        self.travel_speed = travel_speed

        self.debris = []
        self.rotational_component = RotationalComponent([0, 0, 300], [0, 0, 600])
        self.create_rogue_planet(asteroids)

        self.set_pos_hpr_scale(self.start_pos, Vec3(1), scale)
        self.set_texture(base.loader.load_texture('moon_tex.jpg'))

        self.progress = 0.0
        self.is_shattered = False

    def create_rogue_planet(self, asteroids):
        for asteroid in asteroids.get_children():
            default_pos = asteroid.get_pos()
            model = asteroid.copy_to(self)
            debri = Debri(model, default_pos, self.rotational_component)
            self.debris.append(debri)

    def update(self, dt):
        if self.progress <= 1.2:
            self.progress += self.travel_speed * dt
            next_pos = self.start_pos + self.distance * self.progress

            if not self.is_shattered:
                hpr = Vec3(self.get_hpr() + 50 * dt)
                self.set_pos_hpr(next_pos, hpr)

                if self.progress >= 0.85:
                    self.is_shattered = True

                return None

            self.set_pos(next_pos)

        cnt = 0
        for debri in self.debris:
            if debri.update(dt):
                cnt += 1

        return cnt